export const STRINGS = {
  title: "Khoj Q&A Generator",
  description: "Generate Q&A based on uploaded documents",
  version: "(Version: 0.1.0)",
  documentDetails: "Document Details",
  fileName: "File Name *",
  pageLink: "Page Link *", 
  summary: "Summary of Document *",
  numQA: "Number of Q&A",
  generateQA: "Generate Q&A",
  formValidationMessage: "Please fill all the details before generating Q&A.",
  uploadWarning: "Please upload a document to enable this action.",
  uploadButton: "Upload",
  uploadedFile: "Uploaded File",
  invalidFileType:
    "Invalid file type. Only PDF, DOCX, XLS, and CSS are allowed.",
  fileSizeExceeded: "File size exceeds 10MB limit.",
  selectFileFirst: "Please select a file first.",
  uploadFailed: "Upload failed",
  fileReadError: "Failed to read file.",
  previewNotAvailable: "Preview not available",
  submit: 'Submit',
  selectFile:"Select Document to Upload",
  documentUploadSuccess:"Document upload successfully",
  uploading:"Uploading Document..."
};
