export const STRINGS = {
  title: "Q&A Generator",
  description: "Generate Q&A based on uploaded files",
  version: "(Version: 0.1.0)",
  documentDetails: "File Details",
  fileName: "File Name *",
  pageLink: "Reference Link *",
  summary: "File Summary *",
  numQA: "Number of Questions",
  generateQA: "Generate Q&A",
  formValidationMessage: "Please fill all the required fields before generating Q&A.",
  uploadWarning: "Please upload a file to enable this action.",
  uploadButton: "Upload",
  uploadedFile: "Uploaded File",
  invalidFileType:
    "Invalid file type. Only PDF, DOCX, XLS, and CSV are allowed.",
  fileSizeExceeded: "File size exceeds the 10MB limit.",
  selectFileFirst: "Please select a file first.",
  uploadFailed: "Upload failed",
  fileReadError: "Failed to read the file.",
  previewNotAvailable: "Preview not available",
  submit: "Submit",
  selectFile: "Select File to Upload",
  documentUploadSuccess: "File uploaded successfully",
  uploading: "Uploading File...",
  document_submitted_successfully:
    "File has been successfully submitted based on your feedback.",
  something_went_wrong_to_upload: "Something went wrong while uploading the file.",
  pageLinkPlaceHolder:
    "Enter a reference link related to this file, e.g., https://www.hdfcbank.com",
  fileNamePlaceholder: "Enter file name here",
  summaryPlaceHolder:
    "The document provides recommendations for improving services based on research findings.",
  questionPlaceHolder: "Enter the number of questions required for the selected file. (Max. 100)",
  tagPlaceHolder:"Type and press Enter to add a tag",
  sureToDelete:"Are you sure you want to delete this Q&A?",
  addNewQnA_action:"Add New Q&A",
  noQAgenerated: "No Q&A generated yet. Click below to add a new Q&A.",
  answerLabel: "Answer:",
  sectionLabel:"Section:",
  referencesLabel:"References:",
  editQA:"Edit Q&A",
  addQA: "Add New Q&A",
  questionLabel:"Question",
  answer:"Answer",
  pageNumber: "Page Number",
  pageSection:"Page Section",
  saveQA: "Save Q&A",
  cancel: "Cancel",
  special_characters_not_Allowed: "Special characters are not allowed in tags.",
  questionAnswerRequired:"Question and Answer are required!"
};